### ISSUE TITLE
update eclipselink-spring-boot-starter to work with 1.4

### ISSUE THREAD

**Issue by luizkowalski** [zalando-stups/booties#12]
After I upgrade to Spring Boot 1.4, I'm seeing this error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.orm.jpa.EclipselinkJpaAutoconfiguration$$EnhancerBySpringCGLIB$$31f73832]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration: method <init>()V not found
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        ... 32 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration: method <init>()V not found
        at org.springframework.boot.autoconfigure.orm.jpa.EclipselinkJpaAutoconfiguration.<init>(EclipselinkJpaAutoconfiguration.java:53) ~[data-jpa-eclipselink-spring-boot-starter-0.10.0.jar:1.4.0.RELEASE]
        at org.springframework.boot.autoconfigure.orm.jpa.EclipselinkJpaAutoconfiguration$$EnhancerBySpringCGLIB$$31f73832.<init>(<generated>) ~[data-jpa-eclipselink-spring-boot-starter-0.10.0.jar:1.4.0.RELEASE]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_51]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_51]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        ... 34 common frames omitted

[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:483)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.EclipselinkJpaAutoconfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.orm.jpa.EclipselinkJpaAutoconfiguration$$EnhancerBySpringCGLIB$$31f73832]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration: method <init>()V not found
```

Any ideas? seems like in 1.4 the JpaBaseConfiguration now expects a constructor to be implemented in the starter

**Comment by jbellmann** [comment]
I will have a look.

**Comment by jbellmann** [comment]
@luizkowalski could you please try out [0.10.1](https://github.com/zalando-stups/booties/releases/tag/data-jpa-eclipselink-spring-boot-starter-0.10.1) and report back any issues or close this issue if fixed.
Thanks,
Jörg

**Comment by luizkowalski** [comment]
perfect! thanks @jbellmann

**Comment by nkapre** [comment]
Is this issue resolved and verified to be working. I face this issue in Spring Boot 1.4.1 as well. Kindly advise.

**Comment by jbellmann** [comment]
@nkapre at least I hope so :-). @luizkowalski closed the issue and commented in a way that I assume it works. Please verify you use the latest version '0.10.1'.

If it seems you have the latest versions in use and the error still exists. Please provide more information about your project, dependencies or maybe stacktraces.

**Comment by luizkowalski** [comment]
The version 0.10.1 is not on the [repo](https://mvnrepository.com/artifact/org.zalando.stups/spring-boot-starter-data-jpa-eclipselink). I downloaded, installed locally and worked

**Comment by jbellmann** [comment]
All releases made so far are available in maven-central. Upload to maven-central is part of release. Have a look at the 'Maven-Central-Badge'. Or do a search [here](http://search.maven.org/#artifactdetails%7Corg.zalando.stups%7Cdata-jpa-eclipselink-spring-boot-starter%7C0.10.1%7Cjar).

Maybe you already tried it with Spring-Boot 1.4.3.RELEASE? Does it work for you?

Regards
Jörg

**Comment by nkapre** [comment]
The bug does not occur in 1.4.3.

**Comment by jbellmann** [comment]
That's fine. So I will close this issue.
@luizkowalski thanks for fast response regarding this issue.

Regards
Jörg
